generator: admingenerator.generator.doctrine
params:
    model: AppBundle\Entity\Receipt
    namespace_prefix: 
    concurrency_lock: ~
    bundle_name: AppBundle
    pk_requirement: ~
    fields:
        material:
            label: Наименование материала
        quantity:
            label: Количество
        price:
            label: Цена
        description:
            label: Описание
        createdAt:
            label: Создан
        updatedAt:
            label: Обновлен
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Приход материалов
            display: [material, quantity, price, description, createdAt, updatedAt]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title: Новый приход
            display: [quantity, material, price, description]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Вы редактируете приход для \"%object%\"|{ %object%: Receipt.material }|"
            display: [quantity, material, price, description]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "Вы просматриваете приход для \"%object%\"|{ %object%: Receipt.material }|"
            display: [material, quantity, price, description, createdAt, updatedAt]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
