generator: admingenerator.generator.doctrine
params:
    model: AppBundle\Entity\Receipt
    namespace_prefix: 
    concurrency_lock: ~
    bundle_name: AppBundle
    pk_requirement: ~
    fields:
        material:
            label: Наименование материала
        quantity:
            label: Количество
        price:
            label: Цена
            formType: Admingenerator\FormExtensionsBundle\Form\Type\MoneyType
        date:
            label: Дата
            formType: Admingenerator\FormExtensionsBundle\Form\Type\DatePickerType            
        description:
            label: Описание
        createdAt:
            label: Создан
        updatedAt:
            label: Обновлен
        supplier:
            label: Поставщик
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Приход материалов
            display: [material, quantity, price, date, description, supplier, createdAt, updatedAt]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
            filters: [material, quantity, price, date, description, supplier]
            filtersMode: top
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title: Новый приход
            display: [ material, quantity, price, date, description, supplier]
            actions:
                save: ~
                list: ~
            fields: 
                description:   
                    addFormOptions:
                        required: false
    edit:
        params:
            title: "Вы редактируете приход для \"%object%\"|{ %object%: Receipt.material }|"
            display: [ material, quantity, price, date, description, supplier]
            actions:
                save: ~
                list: ~
            fields: 
                description:   
                    addFormOptions:
                        required: false
    show:
        params:
            title: "Вы просматриваете приход для \"%object%\"|{ %object%: Receipt.material }|"
            display: [material, quantity, price, date, description, supplier, createdAt, updatedAt]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
